### PR TITLE
Tna Slot에 셀프패키지 노출

### PR DESCRIPTION
**Pull request by kooinsung**
## PR 설명
관련 쓰레드 : [https://titicaca.slack.com/archives/C9WMUE9DX/p1648522879160739](https://titicaca.slack.com/archives/C9WMUE9DX/p1648522879160739)

## 변경 내역
- bestSelfPackageDiscountSpec 인터페이스 추가

### CODE REVIEW

**Review by inbeom — APPROVED** [review]
👍

**Comment by kooinsung** [comment]
release-canary

**Comment by kooinsung** [comment]
release-canary

**Comment by kooinsung** [comment]
release-canary

**Comment by kooinsung** [comment]
release-canary

**Comment by kooinsung** [comment]
release-canary

**Review by zhsks528 — APPROVED** [review]

**Review by pgs787 — APPROVED** [review]

**Pull request merged**
