### PR TITLE
Test/kint5

### PR DESCRIPTION
**Pull request by jaehyeon48**
triple-korea-frontend

### CODE REVIEW

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-dev

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by inbeom** [comment]
# 2024-01-24

- 서비스 의존성 구분: 서비스 의존성이 없는 로직/컴포넌트는 공유할 수 있는 라이브러리 군
- triple-frontend에서 UI 아닌 것 분리
- **별도의 트리플 글로벌 라이브러리 저장소 생성 & 이 PR에서 변경된 패키지 추가**

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
relese-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by torres-triple** [comment]
release-canary

**Comment by torres-triple** [comment]
release-canary

**Comment by torres-triple** [comment]
release-canary

**Comment by torres-triple** [comment]
release-canary

**Comment by torres-triple** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Comment by jaehyeon48** [comment]
release-canary

**Pull request closed without merging**
