### PR TITLE
[테스트] Epic/improve UI

### PR DESCRIPTION
**Pull request by choisohyun**
## PR 설명

- 카나리배포를 하기 위한 PR입니다. 
  - react 최신버전 등을 TF와 함께 적용시켜 보려고 합니다.

### CODE REVIEW

**Comment by choisohyun** [comment]
release-canary

**Comment by choisohyun** [comment]
release-canary

**Comment by choisohyun** [comment]
src/components/booking-management/common/contact-info-box.tsx

**Comment by choisohyun** [comment]
release-canary

**Comment by choisohyun** [comment]
release-canary

**Comment by drakang4** [comment]
release-canary

**Comment by choisohyun** [comment]
release-canary

**Comment by choisohyun** [comment]
release-canary

**Comment by choisohyun** [comment]
release-canary

**Comment by drakang4** [comment]
release-canary

**Comment by drakang4** [comment]
release-canary

**Comment by drakang4** [comment]
release-canary

**Comment by drakang4** [comment]
release-canary

**Comment by drakang4** [comment]
release-canary

**Comment by choisohyun** [comment]
release-canary

**Comment by choisohyun** [comment]
release-canary

**Comment by choisohyun** [comment]
release-canary

**Pull request closed without merging**
