### PR TITLE
[review] 동영상 리뷰 QA

### PR DESCRIPTION
**Pull request by drakang4**
## PR 설명

https://titicaca.slack.com/archives/C03DA2QG3KK/p1663583741107319
https://titicaca.slack.com/archives/C01PZ4M58G2/p1663729898261629

## 변경 내역

동영상 리뷰 QA에서 발견된 버그 수정입니다.

### CODE REVIEW

**Comment by drakang4** [comment]
release-canary

**Comment by drakang4** [comment]
release-canary

**Comment by drakang4** [comment]
release-canary

**Comment by drakang4** [comment]
release-canary

**Comment by drakang4** [comment]
release-canary

**Comment by drakang4** [comment]
release-canary

**Comment by drakang4** [comment]
release-canary

**Comment by drakang4** [comment]
release-canary

**Comment by drakang4** [comment]
release-canary

**Comment by drakang4** [comment]
release-canary

**Comment by drakang4** [comment]
release-canary

**Review by zhsks528 — APPROVED** [review]

**Review by dongoc — APPROVED** [review]
👍

**Pull request merged**
